fix: try to list the directories that fail

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -43,28 +43,88 @@ jobs:
       - name: moon check
         if: ${{ matrix.os.name != 'windows-latest' }}
         run: |
-          find examples -type f -name "moon.mod.json" -execdir bash -c 'moon install; moon check --target wasm; moon check --target wasm-gc; moon check --target js' \;
-
+          failed_directories=()
+          for dir in examples/*; do
+            if [ -d "$dir" ]; then
+              echo "Processing $dir"
+              if ! (cd "$dir" && moon install && moon check --target wasm && moon check --target wasm-gc && moon check --target js); then
+                echo "Failed in $dir"
+                failed_directories+=("$dir")
+              fi
+            fi
+          done
+          if [ ${#failed_directories[@]} -ne 0 ]; then
+            echo "Commands failed in the following directories:"
+            for dir in "${failed_directories[@]}"; do
+              echo "$dir"
+            done
+            exit 1
+          fi
+    
       - name: moon test
         if: ${{ matrix.os.name != 'windows-latest' }}
         run: |
-          find examples -type f -name "moon.mod.json" -execdir bash -c 'moon test --target wasm; moon test --target wasm-gc; moon test --target js' \;
-
-      - name: moon check on windows
-        if: ${{ matrix.os.name == 'windows-latest' }}
-        run: |
-          Get-ChildItem -Path ".\examples" -Recurse -Filter "moon.mod.json" | ForEach-Object { Set-Location $_.DirectoryName; moon install; moon check --target wasm; moon check --target wasm-gc; moon check --target js }
-
-      - name: moon test on windows
-        if: ${{ matrix.os.name == 'windows-latest' }}
-        run: |
-          Get-ChildItem -Path ".\examples" -Recurse -Filter "moon.mod.json" | ForEach-Object { Set-Location $_.DirectoryName; moon test --target wasm; moon test --target wasm-gc; moon test --target js }
-
+          failed_directories=()
+          for dir in examples/*; do
+            if [ -d "$dir" ]; then
+              echo "Processing $dir"
+              if ! (cd "$dir" && moon test --target wasm && moon test --target wasm-gc && moon test --target js); then
+                echo "Failed in $dir"
+                failed_directories+=("$dir")
+              fi
+            fi
+          done
+          if [ ${#failed_directories[@]} -ne 0 ]; then
+            echo "Commands failed in the following directories:"
+            for dir in "${failed_directories[@]}"; do
+              echo "$dir"
+            done
+            exit 1
+          fi
+      
       - name: check result size
         if: ${{ matrix.os.name != 'windows-latest' }}
         run: |
           find ./target -name '*.wasm' | xargs ls -lh
           find ./target -name '*.js' | xargs ls -lh
+
+      - name: moon check on windows
+        if: ${{ matrix.os.name == 'windows-latest' }}
+        run: |
+          $failed_directories = @()
+          Get-ChildItem -Path ".\examples" -Directory | ForEach-Object {
+            Write-Output "Processing $($_.FullName)"
+            Set-Location $_.FullName
+            if (!(moon install) -or !(moon check --target wasm) -or !(moon check --target wasm-gc) -or !(moon check --target js)) {
+              Write-Output "Failed in $($_.FullName)"
+              $failed_directories += $_.FullName
+            }
+            Set-Location -Path $env:GITHUB_WORKSPACE
+          }
+          if ($failed_directories.Count -ne 0) {
+            Write-Output "Commands failed in the following directories:"
+            $failed_directories | ForEach-Object { Write-Output $_ }
+            exit 1
+          }
+      
+      - name: moon test on windows
+        if: ${{ matrix.os.name == 'windows-latest' }}
+        run: |
+          $failed_directories = @()
+          Get-ChildItem -Path ".\examples" -Directory | ForEach-Object {
+            Write-Output "Processing $($_.FullName)"
+            Set-Location $_.FullName
+            if (!(moon test --target wasm) -or !(moon test --target wasm-gc) -or !(moon test --target js)) {
+              Write-Output "Failed in $($_.FullName)"
+              $failed_directories += $_.FullName
+            }
+            Set-Location -Path $env:GITHUB_WORKSPACE
+          }
+          if ($failed_directories.Count -ne 0) {
+            Write-Output "Commands failed in the following directories:"
+            $failed_directories | ForEach-Object { Write-Output $_ }
+            exit 1
+          }
 
       - name: check result size on windows
         if: ${{ matrix.os.name == 'windows-latest' }}
